config/routes.rb
PowerOf10::Application.routes.draw do
  get "users/index"

  get "users/new"

  get "users/edit"

  namespace :admin do
    resources :essays do
      resources :photos
    end
    resources :users

    root :to => 'dashboard#index'
  end

  resources :essays, :only => [ :index, :show ] do
    collection do
      get :random
    end
  end

  root :to => 'general#index'
end

app/models/essay.rb
class Essay < ActiveRecord::Base
  PHOTO_COUNT = 10

  attr_accessible :description, :title, :lat, :lng, :needs, :location, :map_zoom_level, :is_active, :is_featured, :notes, :contact_name, :contact_email

  validates_presence_of :title, :location, :needs

  belongs_to :user

  has_many :photos

  def needs_list
    output = read_attribute(:needs)
    output = '' if output.nil?
    output.split(/[\n\,]/).collect { |o| o.blank? ? nil : o.strip }.compact
  end

  def first_photo
    photos.order('position ASC').first
  end

  def to_param
    [id, title.parameterize].join("-")
  end
end

app/models/photo.rb
class Photo < ActiveRecord::Base
  attr_accessible :file, :caption, :content_type, :file_size, :height, :position, :width

  mount_uploader :file, PhotoUploader

  belongs_to :essay
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password

  attr_accessible :email, :name, :password
end

app/controllers/admin/application_controller.rb
class Admin::ApplicationController < ActionController::Base
  before_filter :authenticate

  protect_from_forgery

  layout 'admin'

  helper_method :current_user

  private

  def current_user
    @current_user || false
  end

  def authenticate
    if user = authenticate_with_http_basic { |u, p| user = User.find_by_email(u); user && user.authenticate(p) }
      @current_user = user
    else
      request_http_basic_authentication
    end
  end
end

app/controllers/admin/dashboard_controller.rb
class Admin::DashboardController < Admin::ApplicationController
  def index
  end
end

app/controllers/admin/essays_controller.rb
class Admin::EssaysController < Admin::ApplicationController
  before_filter :load_essay, :except => [ :index ]

  respond_to :html

  def index
    @essays = Essay.all
  end

  def show
  end

  def new
  end

  def edit
  end

  def create
    @essay.attributes = params[:essay]

    if @essay.save
      respond_with :admin, @essay, :location => edit_admin_essay_path(@essay)
    else
      respond_with :admin, @essay
    end
  end

  def update
    @essay.attributes = params[:essay]

    @essay.save

    respond_with :admin, @essay
  end

  private

  def load_essay
    @essay = params[:id] ? Essay.find(params[:id]) : Essay.new
  end
end

app/controllers/admin/photos_controller.rb
class Admin::PhotosController < ApplicationController
  before_filter :load_essay
  before_filter :load_photo, :except => [ :index ]

  respond_to :json

  def index
    @photos = @essay.photos
  end

  def new
  end

  def edit
  end

  def update
    @photo.attributes = Photo.filter_attributes(params)

    if @photo.save
      respond_with :admin, @photo, :location => admin_essay_photo_url(@essay.id, @photo.id)
    else
      respond_with :admin, @photo
    end
  end
  alias :create :update

  def destroy
    @photo.destroy

    respond_with @photo
  end

  private

  def load_essay
    @essay = Essay.find_by_id(params[:essay_id])
  end

  def load_photo
    @photo = params[:id] ? @essay.photos.find_by_id(params[:id]) : @essay.photos.build
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < Admin::ApplicationController
  before_filter :require_admin
  before_filter :load_user

  def index
    @users = User.all
  end

  def new
  end

  def edit
  end

  def update
    is_admin = params[:user] && params[:user].delete(:is_admin)

    @user.attributes = params[:user]
    @user.is_admin = is_admin if current_user.is_admin?

    if @user.save
      redirect_to admin_users_path, :notice => 'Changes Saved'
    else
      render :edit
    end
  end
  alias :create :update

  private

  def load_user
    @user = params[:id] ? User.find_by_id(params[:id]) : User.new
  end

  def require_admin
    redirect_to admin_root_path unless @current_user.is_admin?
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/essays_controller.rb
class EssaysController < ApplicationController
  before_filter :load_essay, :except => [ :index, :random ]

  respond_to :html

  def index
    @essays = Essay.all
  end

  def show
  end

  def random
    essay = Essay.where(:is_active => true).order('RANDOM()').first
    redirect_to essay
  end

  private

  def load_essay
    @essay = params[:id] ? Essay.find_by_id_and_is_active(params[:id], true) : Essay.new
  end
end

app/controllers/general_controller.rb
class GeneralController < ApplicationController
  def index
    @essays = Essay.where(:is_active => true, :is_featured => true).order('RANDOM()').limit(2)
  end
end

app/helpers/account_helper.rb
module AccountHelper
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  def map_image_tag(essay, width = 300, height = 300, zoom = nil)
    zoom = essay.map_zoom_level || 8 if zoom.nil?
    image_tag "http://maps.googleapis.com/maps/api/staticmap?center=#{essay.lat},#{essay.lng}&zoom=#{zoom}&size=#{[width, height].join('x')}&sensor=false"
  end

  def textile(text)
    sanitize(RedCloth.new(text, [:filter_html, :filter_styles]).to_html)
  end
end

app/helpers/essays_helper.rb
module EssaysHelper
end

app/helpers/general_helper.rb
module GeneralHelper
end

app/views/admin/dashboard/index.html.erb
<h1>Welcome to the Admin Area</h1>

app/views/admin/essays/_form.html.erb
<%= form_for [:admin, @essay] do |f| %>
  <% if @essay.errors.any? %>
    <% @essay.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
    <% end %>
  <% end %>

  <div id="map-image">
    <% if @essay.lat && @essay.lng %>
      <%= map_image_tag @essay, 300, 200, 8 %>
    <% else %>
    <img />
    <% end %>
  </div>

  <%= f.hidden_field :lat %>
  <%= f.hidden_field :lng %>
  <%= f.hidden_field :map_zoom_level %>

  <p><%= f.text_field :title, :placeholder => 'Title' %></p>
  <p><%= f.text_field :location, :placeholder => 'Location' %></p>
  <p><%= f.text_area :description, :rows => 3, :placeholder => 'Description' %></p>
  <p><%= f.text_area :needs, :rows => 3, :placeholder => 'A Material Scientist, An Engineer, etc' %></p>

<% unless @essay.new_record? %>
  <fieldset>
    <legend>Photos</legend>
    <div class="row-fluid">
      <div class="span6">
        <div id="photos">
          <% @essay.photos.each do |p| %>
            <div class="photo-form" data-photo-id="<%= p.id %>">
              <img src="<%= p.file.thumb.url %>" class="pull-left">
              <input type="text" name="caption" value="<%= p.caption %>"> &mdash; <a class="delete">delete</a>
            </div>
          <% end %>
        </div>
      </div>
      <div class="span6">
        <div id="micro-uploader">
          <div class="padding">
            <div class="select-container"><a class="select-button">Select Files For Upload</a></div>
          </div>
          <div class="file-list hidden">
            <div class="filenames"></div>
          </div>
        </div>
      </div>
    </div>
  </fieldset>

  <fieldset>
    <legend>Admin Details</legend>

    <p><%= f.label :is_active?, :class => 'checkbox' do %>
      <%= f.check_box :is_active %> is active
    <% end %></p>

    <p><%= f.label :is_featured?, :class => 'checkbox' do %>
      <%= f.check_box :is_featured %> is featured
    <% end %></p>

    <p><%= f.text_field :contact_name, :placeholder => 'Contact Name' %></p>
    <p><%= f.text_field :contact_email, :placeholder => 'Contact Email' %></p>

    <p><%= f.text_area :notes, :rows => 5, :placeholder => 'Notes' %></p>
  </fieldset>

<% end %>

  <%= f.submit @essay.new_record? ? 'Next' : 'Save', :class => 'btn btn-primary' %> or <%= link_to 'cancel', admin_essays_path %>
<% end %>

<style type="text/css">
.photo-form { overflow:auto; margin-bottom: 10px; }
.photo-form img { margin-right: 10px; }
.photo-form input[name="caption"] { margin-top: 10px; }
</style>


<script type="text/javascript">
YUI().use('update-photo-caption-on-change', 'remove-photo-on-click', function (Y) {
  Y.App.UpdatePhotoCaptionOnChange(<%= @essay.id %>);
  Y.App.RemovePhotoOnClick(<%= @essay.id %>);
});
</script>

<script type="text/javascript">
YUI().use('autocomplete', function (Y) {
    var acNode = Y.one('#essay_location');

    acNode.plug(Y.Plugin.AutoComplete, {
        // Highlight the first result of the list.
        activateFirstItem: true,

        // The list of the results contains up to 10 results.
        maxResults: 10,

        // To display the suggestions, the minimum of typed chars is five.
        minQueryLength: 3,

        // Number of milliseconds to wait after user input before triggering a
        // `query` event. This is useful to throttle queries to a remote data
        // source.
        queryDelay: 500,

        // Handling the list of results is mandatory, because the service can be
        // unavailable, can return an error, one result, or an array of results.
        // However `resultListLocator` needs to always return an array.
        resultListLocator: function (response) {
            console.log(response);
            // Makes sure an array is returned even on an error.
            if (response.error) {
                return [];
            }

            var query = response.query.results.json,
                addresses;

            if (query.status !== 'OK') {
                return [];
            }

            // Grab the actual addresses from the YQL query.
            addresses = query.results;

            // Makes sure an array is always returned.
            return addresses.length > 0 ? addresses : [addresses];
        },

        // When an item is selected, the value of the field indicated in the
        // `resultTextLocator` is displayed in the input field.
        resultTextLocator: 'formatted_address',

        // {query} placeholder is encoded, but to handle the spaces correctly,
        // the query is has to be encoded again:
        //
        // "my address" -> "my%2520address" // OK => {request}
        // "my address" -> "my%20address"   // OK => {query}
        requestTemplate: function (query) {
            return encodeURI(query);
        },

        // {request} placeholder, instead of the {query} one, this will insert
        // the `requestTemplate` value instead of the raw `query` value for
        // cases where you actually want a double-encoded (or customized) query.
        source: 'SELECT * FROM json WHERE ' +
                    'url="http://maps.googleapis.com/maps/api/geocode/json?' +
                        'sensor=false&' +
                        'address={request}"',

        // Automatically adjust the width of the dropdown list.
        width: 'auto'
    });

    // Adjust the width of the input container.
    acNode.ac.after('resultsChange', function () {
        var newWidth = this.get('boundingBox').get('offsetWidth');
        acNode.setStyle('width', Math.max(newWidth, 150));
    });

    function getZoom(loc) {
      var GLOBE_WIDTH = 256,
        west = loc.southwest.lng,
        east = loc.northeast.lng,
        angle = east - west,
        zoom;

      if (angle < 0) {
        angle += 360;
      }

      zoom = Math.round(Math.log(300 * 360 / angle / GLOBE_WIDTH) / Math.LN2);

      return zoom;
    }

    // Fill the `lat` and `lng` fields when the user selects an item.
    acNode.ac.on('select', function (e) {
        var location = e.result.raw.geometry.location, zoom;

        zoom = getZoom(e.result.raw.geometry.bounds);

        Y.one('#essay_lat').set('value', location.lat);
        Y.one('#essay_lng').set('value', location.lng);
        Y.one('#essay_map_zoom_level').set('value', zoom);
        Y.one('#map-image img').set('src', 'http://maps.googleapis.com/maps/api/staticmap?center=' + location.lat + ',' + location.lng + '&zoom=' + zoom + '&size=300x200&sensor=false').show();
    });
});
</script>

<script>
YUI({filter:"raw"}).use("uploader", "json", "transition", function(Y) {
  var container = Y.one('#micro-uploader'),
    csrfToken = Y.one('meta[name="csrf-token"]').getAttribute('content');

  // container.one(".progress").set("text", "Uploader type: " + Y.Uploader.TYPE);

  if (Y.one('#micro-uploader')) {
    if (Y.Uploader.TYPE != "none" && !Y.UA.ios) {
      var uploader = new Y.Uploader({
                                      multipleFiles: true,
                                      uploadURL: "/admin/essays/<%= @essay.id %>/photos",
                                      simLimit: 2,
                                      withCredentials: false,
                                      fileFieldName: 'file',
                                      uploadHeaders: { 'X-CSRF-Token': csrfToken },
                                      selectFilesButton: container.one('.select-button')
                                    });
      var uploadDone = false;

      if (Y.Uploader.TYPE == "html5") {
        uploader.set("dragAndDropArea", "#micro-uploader .select-container");

        // Y.one("#ddmessage").setHTML("<strong>Drag and drop files here.</strong>");

        uploader.on(["dragenter", "dragover"], function (event) {
            var dd = event.target.get('dragAndDropArea');
            dd.addClass("yellowBackground");
         });

         uploader.on(["dragleave", "drop"], function (event) {
            var dd = event.target.get('dragAndDropArea');
            dd.removeClass("yellowBackground");
         });
      }

      uploader.render("#micro-uploader .select-container");

      uploader.after("fileselect", function (event) {

        var fileList = event.fileList;
        var fileTable = container.one(".filenames");

        if (fileList.length > 0 && Y.one("#nofiles")) {
          Y.one("#nofiles").remove();
        }

        if (uploadDone) {
          uploadDone = false;
          fileTable.setHTML("");
        }

        Y.each(fileList, function (fileInstance) {
          fileTable.append("<div id='" + fileInstance.get("id") + "_row" + "'>" +
                                "<span class='filename'>" + fileInstance.get("name") + "</span>" +
                                "<span class='percentdone'></span>" +
                                "</div>");
        });

        container.one('.file-list').removeClass('hidden');
      });

      uploader.after("fileListChange", function (event) {
        if (!uploadDone && uploader.get("fileList").length > 0) {
          uploader.uploadAll();
        }
      });

      uploader.on("uploadprogress", function (event) {
        var fileRow = Y.one("#" + event.file.get("id") + "_row");
        console.log("uploadprogress", event, fileRow, fileRow.one(".percentdone"), event.percentLoaded);
        fileRow.one(".percentdone").setStyle("width", event.percentLoaded + "%");
      });

      uploader.on("uploaderror", function (event) {
        console.log(event, event.data);
        var fileRow = Y.one("#" + event.file.get("id") + "_row");
        fileRow.addClass('error').append('<i abbr="' + event.statusText + '">?</i>');
      });

      uploader.on("uploadcomplete", function (event) {
        var fileRow = Y.one("#" + event.file.get("id") + "_row"),
            response = Y.JSON.parse(event.data);
        console.log(fileRow, response)
        fileRow.one(".percentdone").setStyle("width", "100%");
        if (response.hasOwnProperty('errors')) {
          fileRow.addClass('error').append('<i abbr="there was an error">?</i>');
        } else {
          Y.one('#photos').append('<div class="photo-form" data-photo-id="' + response.id + '"><img src="' + response.file.thumb.url + '" class="pull-left"><input type="text" name="caption" value="' + (response.caption || '') + '"></div>');
          setTimeout(function () {
            fileRow.hide('fadeOut', {}, function () {
              Y.one(this).remove();
              if (container.one('.filenames').get('children').size() == 0) {
                container.one('.file-list').addClass("hidden")
              }
            });
          }, 3000)
        }
      });

      uploader.on("alluploadscomplete", function (event) {
        uploader.set("fileList", []);
        uploadDone = true;
      });
    } else {
        Y.one("#micro-uploader").set("text", "We are sorry, but to use the uploader, you either need a browser that support HTML5 or have the Flash player installed on your computer.");
    }
  }

});

</script>

app/views/admin/essays/edit.html.erb
<div class="page-header">
  <h1>Edit Your Essay</h1>
</div>

<%= render 'form' %>

app/views/admin/essays/index.html.erb
<div class="page-header">
  <div class="pull-right">
    <%= link_to 'New Essay', new_admin_essay_path, :class => 'btn' %>
  </div>
  <h1>Essays</h1>
</div>

<table class="table table-striped">
  <tr>
    <th>Title</th>
    <th>Country</th>
    <th>Is Active?</th>
    <th>Is Featured?</th>
    <th>&nbsp;</th>
  </tr>
  <% @essays.each do |essay| %>
  <tr>
    <td><%= link_to essay.title, [:admin, essay] %></td>
    <td><%= essay.location %></td>
    <td><%= essay.is_active? %></td>
    <td><%= essay.is_featured? %></td>
    <td><%= link_to 'Edit', edit_admin_essay_path(essay) %></td>
  </tr>
  <% end %>
</table>

app/views/admin/essays/new.html.erb
<div class="page-header">
  <h1>Create Your Essay</h1>
</div>

<%= render 'form' %>

app/views/admin/essays/show.html.erb
<div class="page-header">
  <div class="pull-right">
    <%= link_to 'Edit', edit_admin_essay_path(@essay), :class => 'btn' %>
  </div>

  <h1><%= @essay.title %> &mdash; <%= @essay.location %></h1>
  <small>Needs: <%= @essay.needs_list.to_sentence %></small>
</div>

<% if @essay.photos.size > 0 %>
  <div class="photos">
  <% @essay.photos.each do |photo| %>
    <div class="photo">
      <%= image_tag photo.file.small.url %>
      <%= textile(photo.caption || 'No Caption') %>
    </div>
  <% end %>
  </div>
<% else %>
<p>There are no photos for this essay.</p>
<% end %>

<style type="text/css">
.photos .photo { position: relative; float: left; margin-right: 10px; margin-bottom: 10px; }
.photos .photo p { position: absolute; bottom: 0; left: 0; right: 0; color: #fff; background-color: rgba(0,0,0,0.5); padding: 10px; margin: 0; }
</style>

app/views/admin/photos/edit.html.erb
<h1>Admin::Photos#edit</h1>
<p>Find me in app/views/admin/photos/edit.html.erb</p>

app/views/admin/photos/index.html.erb
<h1>Admin::Photos#index</h1>
<p>Find me in app/views/admin/photos/index.html.erb</p>

app/views/admin/photos/new.html.erb
<h1>Admin::Photos#new</h1>
<p>Find me in app/views/admin/photos/new.html.erb</p>

app/views/admin/users/_form.html.erb
<%= form_for [:admin, @user] do |f| %>
  <p><%= f.label :name %> <%= f.text_field :name %></p>
  <p><%= f.label :email %> <%= f.text_field :email %></p>
  <p><%= f.label :password %> <%= f.text_field :password %><%= content_tag('span', 'Leave blank to keep it the same', :class => 'help-inline') unless @user.new_record? %></p>
  <% if current_user.is_admin? %>
  <p><%= f.label :is_admin?, :class => 'checkbox' do %>
       <%= f.check_box :is_admin %> Is an admin account
     <% end %></p>
  <% end %>
  <div class="actions">
    <%= f.submit 'Save', :class => 'btn btn-primary' %> or <%= link_to 'cancel', admin_users_path %>
  </div>
<% end %>

app/views/admin/users/edit.html.erb
<div class="page-header">
  <h1>Edit <%= @user.name %>'s Account</h1>
</div>

<%= render 'form' %>

app/views/admin/users/index.html.erb
<div class="page-header">
  <div class="pull-right">
    <%= link_to 'New User', new_admin_user_path, :class => 'btn' %>
  </div>
  <h1>Users</h1>
</div>

<table class="table table-striped">
  <tr>
    <th>Name</th>
    <th>Email</th>
    <th>Is Admin?</th>
    <th>&nbsp;</th>
  </tr>
  <% @users.each do |user| %>
  <tr>
    <td><%= user.name %></td>
    <td><%= user.email %></td>
    <td><%= user.is_admin? %></td>
    <td><%= link_to 'Edit', edit_admin_user_path(user) %></td>
  </tr>
  <% end %>
</table>

app/views/admin/users/new.html.erb
<div class="page-header">
  <h1>Add a new User</h1>
</div>

<%= render 'form' %>

app/views/essays/_preview.html.erb
<div class="essay-preview">
  <div class="row">
    <div class="span4">
      <% if preview.first_photo %>
      <%= link_to(image_tag(preview.first_photo.file.small.url, :class => 'photo'), preview) %>
      <% else %>
      <p>No photos</p>
      <% end %>
    </div>
    <div class="span4">
      <% image_tag "http://api.tiles.mapbox.com/v3/mapbox.mapbox-light/#{preview.lng},#{preview.lat},10/300x300.png" %>
      <%= map_image_tag preview %>
    </div>
    <div class="span4">
      <h3><strong><%= preview.location %></strong> needs...</h3>
      <% preview.needs_list.each do |n| %>
      <p><span><%= n %></span></p>
      <% end %>
      <%= link_to 'Find out more...', preview, :class => 'btn btn-warning btn-large' %>
    </div>
  </div>
</div>

app/views/essays/show.html.erb
<%= link_to 'Home', root_path %>

<div class="page-header">
  <h1><%= @essay.title %></h1>
</div>

<% if @essay.first_photo %>
<div id="photo" data-number="1">
  <div class="row">
    <div class="span8">
      <%= image_tag @essay.first_photo.file.url, :class => 'photo' %>
    </div>
    <div class="span4">
      <div class="caption">
        <%= textile @essay.first_photo.caption %>
      </div>
    </div>
  </div>
</div>
<% end %>

<div id="action"<%= ' style="display: none"'.html_safe if @essay.first_photo %>>
  <p><%= @essay.location %> needs <%= @essay.needs_list.to_sentence %></p>
  <p><%= link_to 'Start Over', @essay, :class => 'start-over' %></p>
  <p><%= link_to 'View another essay', random_essays_path %></p>
</div>

<% if @essay.first_photo %>
<script type="text/javascript">
YUI().use('node', function (Y) {
  window.PhotoBrowser(<%= @essay.photos.collect { |p| { caption: textile(p.caption), url: p.file.url } }.to_json.html_safe %>);
});
</script>
<% end %>

app/views/general/index.html.erb
<div class="page-header">
  <h1>Power of 10 <small>10 Photos :: 10 Minutes :: Share your skills with the world</small></h1>
</div>

<%= render :partial => 'essays/preview', :collection => @essays %>

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>PowerOf10</title>
  <%= stylesheet_link_tag    "admin", :media => "all" %>
  <%= javascript_include_tag "admin" %>
  <%= csrf_meta_tags %>
</head>
<body>

<div class="navbar navbar-static-top">
  <div class="navbar-inner">
    <a class="brand" href="/admin/">10power Admin</a>
    <ul class="nav">
      <li><a href="/admin/">Home</a></li>
      <li><a href="/admin/essays">Essays</a></li>
      <% if current_user.is_admin? %>
      <li><a href="/admin/users">Users</a></li>
      <% end %>
    </ul>
  </div>
</div>

<div class="container">
  <%= yield %>
</div>

</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>PowerOf10</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<div class="container">
  <%= yield %>
</div>

</body>
</html>